import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { logAudit } from "@/lib/audit";
import { spawn, execFile } from "child_process";
import { promisify } from "util";
import fs from "fs";
import path from "path";

const execFileAsync = promisify(execFile);

/**
 * Automatically resolve the correct Python executable on the host system.
 * Handles RHEL/Linux (where it is 'python3') and Windows/Virtualenv (where it is 'python').
 */
async function resolvePythonCommand(): Promise<string> {
    if (process.env.PYTHON_PATH) return process.env.PYTHON_PATH;
    const candidates = process.platform === "win32" ? ["python", "python3", "py"] : ["python3", "python"];
    for (const cmd of candidates) {
        try {
            await execFileAsync(cmd, ["--version"]);
            return cmd;
        } catch {
            // continue candidate probe
        }
    }
    return process.platform === "win32" ? "python" : "python3";
}

function normalizeHost(host: string): string {
    return host.split(".")[0].trim();
}

function correlateLinks(devices: any[]): any[] {
    const deviceMap = new Map<string, any>();
    for (const d of devices) {
        deviceMap.set(d.hostname, d);
        deviceMap.set(d.hostname.toLowerCase(), d);
    }

    const seenPairs = new Set<string>();
    const links: any[] = [];

    for (const dev of devices) {
        if (dev.status !== "REACHABLE") continue;

        for (const cdp of (dev.cdp_neighbors || [])) {
            if (cdp.is_ap) continue;

            const remoteHost = normalizeHost(cdp.destination_host);
            const localIntf = cdp.local_interface;
            const remoteIntf = cdp.remote_interface;

            const pairItems = [
                `${dev.hostname}:${localIntf}`,
                `${remoteHost}:${remoteIntf}`
            ].sort();
            const pairKey = pairItems.join(" <-> ");

            if (seenPairs.has(pairKey)) continue;
            seenPairs.add(pairKey);

            const srcIntf = dev.interfaces?.[localIntf];
            const remoteDev = deviceMap.get(remoteHost) || deviceMap.get(remoteHost.toLowerCase());
            const dstIntf = remoteDev?.interfaces?.[remoteIntf];

            let linkType = "L2_TRUNK";
            if (srcIntf?.is_trunk) {
                linkType = "L2_TRUNK";
            } else if (srcIntf?.ip_address || dstIntf?.ip_address) {
                linkType = "L3_ROUTED";
            } else if (dev.role === "Router" || remoteDev?.role === "Router") {
                linkType = "L3_ROUTED";
            }

            links.push({
                sourceDevice: dev.hostname,
                sourceInterface: localIntf,
                sourceIp: srcIntf?.ip_address || null,
                targetDevice: remoteHost,
                targetInterface: remoteIntf,
                targetIp: dstIntf?.ip_address || null,
                linkType,
                status: "UP"
            });
        }
    }

    return links;
}

async function persistLatestSnapshot(
    crawlerDir: string,
    seeds: string[],
    profile: string,
    maxHops: number,
    label: string,
    useMock: boolean,
    session: any
) {
    const snapshotsDir = path.join(crawlerDir, "snapshots");
    const files = fs.readdirSync(snapshotsDir)
        .filter(f => f.startsWith("snapshot_") && f.endsWith(".json"))
        .map(f => ({
            name: f,
            time: fs.statSync(path.join(snapshotsDir, f)).mtimeMs
        }))
        .sort((a, b) => b.time - a.time);

    if (files.length === 0) {
        throw new Error("No snapshot JSON file was generated by the crawler.");
    }

    const latestFile = path.join(snapshotsDir, files[0].name);
    const snapshotData = JSON.parse(fs.readFileSync(latestFile, "utf-8"));
    const meta = snapshotData.metadata;

    const lastSnap = await prisma.crawlSnapshot.findFirst({
        orderBy: { snapshotNumber: "desc" }
    });
    const nextSnapshotNumber = (lastSnap?.snapshotNumber || 0) + 1;

    const newSnapshot = await prisma.crawlSnapshot.create({
        data: {
            snapshotNumber: nextSnapshotNumber,
            timestamp: new Date(meta.timestamp.replace(" ", "T")),
            seedDevices: meta.seed_devices || seeds,
            totalDiscovered: meta.total_discovered || snapshotData.devices.length,
            totalReachable: meta.total_reachable || snapshotData.devices.filter((d: any) => d.status === "REACHABLE").length,
            totalUnreachable: meta.total_unreachable || snapshotData.devices.filter((d: any) => d.status !== "REACHABLE").length,
            durationSeconds: meta.duration_seconds || 1.5,
            crawlProfile: (meta.crawl_profile || profile).toUpperCase(),
            maxHops: meta.max_hops ?? maxHops,
            reseedFrontier: meta.reseed_points || [],
        }
    });

    for (const dev of snapshotData.devices) {
        await prisma.crawlDevice.create({
            data: {
                snapshotId: newSnapshot.id,
                hostname: dev.hostname,
                ipAddress: dev.ip_address,
                platform: dev.platform,
                osVersion: dev.os_version,
                serialNumber: dev.serial_number,
                role: dev.role,
                status: dev.status,
                failureReason: dev.failure_reason,
                discoveredVia: dev.discovered_via,
                credentialUsed: dev.credential_used || null,
                authTimeMs: dev.auth_time_ms ?? null,
                hopDistance: dev.hop_distance ?? 0,
                isReseedFrontier: Boolean(dev.is_reseed_frontier),
                boundaryNeighbors: dev.boundary_neighbors || [],
                site: dev.site_info?.site || null,
                idf: dev.site_info?.idf || null,
                roleCode: dev.site_info?.role_code || null,
                iterator: dev.site_info?.iterator || null,
                interfaces: dev.interfaces || {},
                routes: dev.routes || [],
                vlans: dev.vlans || [],
                cdpNeighbors: dev.cdp_neighbors || [],
                arpTable: dev.arp_table || []
            }
        });
    }

    const links = correlateLinks(snapshotData.devices);
    for (const link of links) {
        await prisma.crawlLink.create({
            data: {
                snapshotId: newSnapshot.id,
                sourceDevice: link.sourceDevice,
                sourceInterface: link.sourceInterface,
                sourceIp: link.sourceIp,
                targetDevice: link.targetDevice,
                targetInterface: link.targetInterface,
                targetIp: link.targetIp,
                linkType: link.linkType,
                status: link.status
            }
        });
    }

    await logAudit(
        'CRAWLER_TRIGGER',
        `Executed ${useMock ? 'Virtual Mock Lab' : 'Live SSH'} Network Crawl. Created Snapshot #${newSnapshot.snapshotNumber} with ${snapshotData.devices.length} devices.`,
        (session?.user as any)?.id,
        (session?.user as any)?.ipAddress
    );

    return newSnapshot;
}

export async function POST(request: NextRequest) {
    try {
        const session = await auth();
        if ((session?.user as any)?.role !== 'ADMIN') {
            return NextResponse.json({ error: "Forbidden: Administrator access required." }, { status: 403 });
        }

        const body = await request.json().catch(() => ({}));
        const useMock = body.useMock !== false;
        const seeds = Array.isArray(body.seeds) && body.seeds.length > 0 ? body.seeds : ["10.100.1.1"];
        const workers = body.workers || 10;
        const profile = typeof body.profile === "string" ? body.profile.toLowerCase() : "intensive";
        const rawHops = body.maxHops !== undefined && body.maxHops !== null ? Number(body.maxHops) : 1;
        const maxHops = Math.min(Math.max(isNaN(rawHops) ? 1 : rawHops, 1), 10);
        const enableLldp = Boolean(body.enableLldp);

        const crawlerDir = path.join(process.cwd(), "services", "crawler");
        const pythonBin = await resolvePythonCommand();

        const args = ["main.py", "crawl"];
        if (useMock) {
            args.push("--mock");
        } else {
            args.push("--seeds", seeds.join(","), "--workers", String(workers));
        }

        args.push("--profile", profile);
        args.push("--max-hops", String(maxHops));
        if (enableLldp) {
            args.push("--enable-lldp");
        }

        const customEnv: Record<string, string> = {
            PYTHONPATH: crawlerDir,
            PYTHONUNBUFFERED: "1",
            PYTHONIOENCODING: "utf-8",
            NO_COLOR: "1" // Disable ANSI escape sequences for pure clean streaming logs
        };
        if (body.username) customEnv.NETCRAWL_USER = String(body.username).trim();
        if (body.password) customEnv.NETCRAWL_PASS = String(body.password);
        if (body.secret) customEnv.NETCRAWL_SECRET = String(body.secret);

        console.log(`[CRAWLER-TRIGGER] Using python: ${pythonBin} | args: ${args.join(" ")} in ${crawlerDir}`);

        const encoder = new TextEncoder();
        const stream = new ReadableStream({
            start(controller) {
                const sendEvent = (obj: any) => {
                    try {
                        controller.enqueue(encoder.encode(`data: ${JSON.stringify(obj)}\n\n`));
                    } catch {
                        // stream might be closed by client
                    }
                };

                sendEvent({
                    type: "status",
                    message: `[INIT] Resolved Python: ${pythonBin} | Profile: ${profile.toUpperCase()} | Depth: ${maxHops} Hop(s)`
                });

                if (!useMock) {
                    sendEvent({
                        type: "status",
                        message: `[SSH] Connecting to seed(s): ${seeds.join(", ")} (User: ${body.username || "server-default"})...`
                    });
                }

                const proc = spawn(pythonBin, args, {
                    cwd: crawlerDir,
                    env: {
                        ...process.env,
                        ...customEnv
                    }
                });

                // Abort process if client disconnects
                request.signal.addEventListener("abort", () => {
                    try {
                        proc.kill();
                    } catch {
                        // ignore
                    }
                });

                proc.stdout.on("data", (chunk: Buffer) => {
                    const text = chunk.toString("utf-8");
                    const lines = text.split(/\r?\n/).filter(l => l.trim().length > 0);
                    for (const line of lines) {
                        sendEvent({ type: "log", line: line.trim() });
                    }
                });

                proc.stderr.on("data", (chunk: Buffer) => {
                    const text = chunk.toString("utf-8");
                    const lines = text.split(/\r?\n/).filter(l => l.trim().length > 0);
                    for (const line of lines) {
                        sendEvent({ type: "stderr", line: line.trim() });
                    }
                });

                proc.on("error", (err) => {
                    sendEvent({ type: "error", error: `Failed to spawn crawler binary (${pythonBin}): ${err.message}` });
                    try { controller.close(); } catch {}
                });

                proc.on("close", async (code) => {
                    if (code !== 0) {
                        sendEvent({
                            type: "error",
                            error: `Crawler process exited with error code ${code}. Review logs above for details.`
                        });
                        try { controller.close(); } catch {}
                        return;
                    }

                    try {
                        sendEvent({ type: "status", message: `[DB] Parsing crawler snapshot and persisting to PostgreSQL...` });
                        const newSnapshot = await persistLatestSnapshot(
                            crawlerDir,
                            seeds,
                            profile,
                            maxHops,
                            body.name || "Crawl Snapshot",
                            useMock,
                            session
                        );
                        sendEvent({
                            type: "done",
                            snapshotId: newSnapshot.id,
                            snapshotNumber: newSnapshot.snapshotNumber,
                            totalDiscovered: newSnapshot.totalDiscovered,
                            totalReachable: newSnapshot.totalReachable,
                            totalUnreachable: newSnapshot.totalUnreachable
                        });
                    } catch (persistErr: any) {
                        sendEvent({ type: "error", error: `Failed saving snapshot to database: ${persistErr.message}` });
                    } finally {
                        try { controller.close(); } catch {}
                    }
                });
            }
        });

        return new Response(stream, {
            headers: {
                "Content-Type": "text/event-stream; charset=utf-8",
                "Cache-Control": "no-cache, no-transform",
                "Connection": "keep-alive"
            }
        });
    } catch (error: any) {
        console.error("Failed to execute network crawl:", error);
        return NextResponse.json({
            error: `Crawl execution failed: ${error.message || String(error)}`
        }, { status: 500 });
    }
}
