import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { logAudit } from "@/lib/audit";
import { execFile } from "child_process";
import { promisify } from "util";
import fs from "fs";
import path from "path";

const execFileAsync = promisify(execFile);

function normalizeHost(host: string): string {
    return host.split(".")[0].trim();
}

function correlateLinks(devices: any[]): any[] {
    const deviceMap = new Map<string, any>();
    for (const d of devices) {
        deviceMap.set(d.hostname, d);
        deviceMap.set(d.hostname.toLowerCase(), d);
    }

    const seenPairs = new Set<string>();
    const links: any[] = [];

    for (const dev of devices) {
        if (dev.status !== "REACHABLE") continue;

        for (const cdp of (dev.cdp_neighbors || [])) {
            if (cdp.is_ap) continue;

            const remoteHost = normalizeHost(cdp.destination_host);
            const localIntf = cdp.local_interface;
            const remoteIntf = cdp.remote_interface;

            const pairItems = [
                `${dev.hostname}:${localIntf}`,
                `${remoteHost}:${remoteIntf}`
            ].sort();
            const pairKey = pairItems.join(" <-> ");

            if (seenPairs.has(pairKey)) continue;
            seenPairs.add(pairKey);

            const srcIntf = dev.interfaces?.[localIntf];
            const remoteDev = deviceMap.get(remoteHost) || deviceMap.get(remoteHost.toLowerCase());
            const dstIntf = remoteDev?.interfaces?.[remoteIntf];

            let linkType = "L2_TRUNK";
            if (srcIntf?.is_trunk) {
                linkType = "L2_TRUNK";
            } else if (srcIntf?.ip_address || dstIntf?.ip_address) {
                linkType = "L3_ROUTED";
            } else if (dev.role === "Router" || remoteDev?.role === "Router") {
                linkType = "L3_ROUTED";
            }

            links.push({
                sourceDevice: dev.hostname,
                sourceInterface: localIntf,
                sourceIp: srcIntf?.ip_address || null,
                targetDevice: remoteHost,
                targetInterface: remoteIntf,
                targetIp: dstIntf?.ip_address || null,
                linkType,
                status: "UP"
            });
        }
    }

    return links;
}

export async function POST(request: NextRequest) {
    try {
        const session = await auth();
        if ((session?.user as any)?.role !== 'ADMIN') {
            return NextResponse.json({ error: "Forbidden: Administrator access required." }, { status: 403 });
        }

        const body = await request.json().catch(() => ({}));
        const useMock = body.useMock !== false; // default true for safety unless explicitly disabled
        const seeds = Array.isArray(body.seeds) && body.seeds.length > 0 ? body.seeds : ["10.100.1.1"];
        const workers = body.workers || 10;

        const crawlerDir = path.join(process.cwd(), "services", "crawler");
        const mainPy = path.join(crawlerDir, "main.py");

        const args = ["main.py", "crawl"];
        if (useMock) {
            args.push("--mock");
        } else {
            args.push("--seeds", seeds.join(","), "--workers", String(workers));
        }

        console.log(`[CRAWLER-TRIGGER] Running: python ${args.join(" ")} in ${crawlerDir}`);

        // Execute python crawler
        const { stdout, stderr } = await execFileAsync("python", args, {
            cwd: crawlerDir,
            timeout: 120000,
            env: {
                ...process.env,
                PYTHONIOENCODING: "utf-8"
            }
        });

        // Find the newly generated snapshot JSON file in snapshots/
        const snapshotsDir = path.join(crawlerDir, "snapshots");
        const files = fs.readdirSync(snapshotsDir)
            .filter(f => f.startsWith("snapshot_") && f.endsWith(".json"))
            .map(f => ({
                name: f,
                time: fs.statSync(path.join(snapshotsDir, f)).mtimeMs
            }))
            .sort((a, b) => b.time - a.time);

        if (files.length === 0) {
            throw new Error("No snapshot file generated by crawler process.");
        }

        const latestFile = path.join(snapshotsDir, files[0].name);
        const snapshotData = JSON.parse(fs.readFileSync(latestFile, "utf-8"));
        const meta = snapshotData.metadata;

        // Determine next snapshot number in PostgreSQL
        const lastSnap = await prisma.crawlSnapshot.findFirst({
            orderBy: { snapshotNumber: "desc" }
        });
        const nextSnapshotNumber = (lastSnap?.snapshotNumber || 0) + 1;

        // Persist to PostgreSQL
        const newSnapshot = await prisma.crawlSnapshot.create({
            data: {
                snapshotNumber: nextSnapshotNumber,
                timestamp: new Date(meta.timestamp.replace(" ", "T")),
                seedDevices: meta.seed_devices || seeds,
                totalDiscovered: meta.total_discovered || snapshotData.devices.length,
                totalReachable: meta.total_reachable || snapshotData.devices.filter((d: any) => d.status === "REACHABLE").length,
                totalUnreachable: meta.total_unreachable || snapshotData.devices.filter((d: any) => d.status !== "REACHABLE").length,
                durationSeconds: meta.duration_seconds || 1.5
            }
        });

        // Insert Devices
        for (const dev of snapshotData.devices) {
            await prisma.crawlDevice.create({
                data: {
                    snapshotId: newSnapshot.id,
                    hostname: dev.hostname,
                    ipAddress: dev.ip_address,
                    platform: dev.platform,
                    osVersion: dev.os_version,
                    serialNumber: dev.serial_number,
                    role: dev.role,
                    status: dev.status,
                    failureReason: dev.failure_reason,
                    discoveredVia: dev.discovered_via,
                    site: dev.site_info?.site || null,
                    idf: dev.site_info?.idf || null,
                    roleCode: dev.site_info?.role_code || null,
                    iterator: dev.site_info?.iterator || null,
                    interfaces: dev.interfaces || {},
                    routes: dev.routes || [],
                    vlans: dev.vlans || [],
                    cdpNeighbors: dev.cdp_neighbors || [],
                    arpTable: dev.arp_table || []
                }
            });
        }

        // Correlate and Insert Links
        const links = correlateLinks(snapshotData.devices);
        for (const link of links) {
            await prisma.crawlLink.create({
                data: {
                    snapshotId: newSnapshot.id,
                    sourceDevice: link.sourceDevice,
                    sourceInterface: link.sourceInterface,
                    sourceIp: link.sourceIp,
                    targetDevice: link.targetDevice,
                    targetInterface: link.targetInterface,
                    targetIp: link.targetIp,
                    linkType: link.linkType,
                    status: link.status
                }
            });
        }

        // Audit Log
        await logAudit(
            'CRAWLER_TRIGGER',
            `Executed ${useMock ? 'Virtual Mock Lab' : 'Live SSH'} Network Crawl. Created Snapshot #${newSnapshot.snapshotNumber} with ${snapshotData.devices.length} devices.`,
            (session?.user as any)?.id,
            (session?.user as any)?.ipAddress
        );

        return NextResponse.json({
            success: true,
            snapshotId: newSnapshot.id,
            snapshotNumber: newSnapshot.snapshotNumber,
            totalDiscovered: newSnapshot.totalDiscovered,
            totalReachable: newSnapshot.totalReachable,
            totalUnreachable: newSnapshot.totalUnreachable,
            message: `Crawl completed successfully! Created Snapshot #${newSnapshot.snapshotNumber} in PostgreSQL.`
        });
    } catch (error: any) {
        console.error("Failed to execute network crawl:", error);
        return NextResponse.json({
            error: `Crawl execution failed: ${error.message || String(error)}`
        }, { status: 500 });
    }
}
